version: '3'
services:
  webserver:
    build:
      context: .
      dockerfile: docker/webserver/Dockerfile
    ports:
      - "8080:80"
    networks:
      - backend
    tty: true
    stdin_open: true
    volumes:
      - .:/var/www:ro
      - ./var:/var/www/var
    links:
      - database
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.2.22"
      PHP_IDE_CONFIG: "serverName=localhostXdebugDocker"
  database:
    build:
      context: .
      dockerfile: docker/database/Dockerfile
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'root'
      MYSQL_PASS: 'root'
      MYSQL_DATABASE: 'shop'
    ports:
      - "3306:3306"
    networks:
      - backend
    tty: true
    stdin_open: true
    restart: always
networks:
  backend:
