version: '3'
services:
  webserver:
    build:
      context: .
      dockerfile: docker/webserver/Dockerfile
    ports:
      - "8080:80"
    networks:
      - backend
    tty: true
    stdin_open: true
    volumes:
      - .:/var/www:ro
    links:
      - database
  database:
    build:
      context: .
      dockerfile: docker/database/Dockerfile
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'root'
      MYSQL_PASS: 'root'
    ports:
      - "3306:3306"
    networks:
      - backend
    tty: true
    stdin_open: true
    restart: always
networks:
  backend:
