version: '3'
services:
#  webserver:
#    build:
#      context: .
#      dockerfile: docker/webserver/Dockerfile
#    ports:
#      - "5000:5000"
  database:
    build:
      context: .
      dockerfile: docker/database/Dockerfile
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'root'
      MYSQL_PASS: 'root'
    ports:
      - "3306:3306"
    networks:
      - backend
    tty: true
    stdin_open: true
    restart: always
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    networks:
      - backend
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    links:
      - database
networks:
  backend:
