# this dockerfile is only for local development
# do not use this configuration for production systems

FROM mysql:5.7
MAINTAINER Felix Ohnesorge <felix.ohnesorge@8qfx1ai5.de>

#RUN echo "default_authentication_plugin=mysql_native_password" >> /etc/mysql/my.cnf
